name: CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn verify
  deploy:
    needs: build  #If you have a job that must only run after another job has completed, you can use the needs keyword to create this dependency.
    runs-on: ubuntu-latest
    name: Deploy to Fly.io
    steps:
      # check out repository and flyctl deploy
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --app money-transfer-api-act23
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_TOKEN_SMS }}